// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX1mBhegfYr-q-UXpVOwxVSpY1ErSd97s',
    appId: '1:341358061781:web:49393409ff86a19b061a5c',
    messagingSenderId: '341358061781',
    projectId: 'happyschool-56835',
    authDomain: 'happyschool-56835.firebaseapp.com',
    storageBucket: 'happyschool-56835.firebasestorage.app',
    measurementId: 'G-Z7EKSB0TWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdEL0sKmAiPX02eYn4SHmDRLSa6Wp2gC4',
    appId: '1:341358061781:android:501494e388592370061a5c',
    messagingSenderId: '341358061781',
    projectId: 'happyschool-56835',
    storageBucket: 'happyschool-56835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGP-QvqFkzWQiZx7V9pxoZqjeiqxRT-hE',
    appId: '1:341358061781:ios:d9b1a616d379a04f061a5c',
    messagingSenderId: '341358061781',
    projectId: 'happyschool-56835',
    storageBucket: 'happyschool-56835.firebasestorage.app',
    iosBundleId: 'com.example.happySchoolFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGP-QvqFkzWQiZx7V9pxoZqjeiqxRT-hE',
    appId: '1:341358061781:ios:d9b1a616d379a04f061a5c',
    messagingSenderId: '341358061781',
    projectId: 'happyschool-56835',
    storageBucket: 'happyschool-56835.firebasestorage.app',
    iosBundleId: 'com.example.happySchoolFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX1mBhegfYr-q-UXpVOwxVSpY1ErSd97s',
    appId: '1:341358061781:web:b4d4c222d7596905061a5c',
    messagingSenderId: '341358061781',
    projectId: 'happyschool-56835',
    authDomain: 'happyschool-56835.firebaseapp.com',
    storageBucket: 'happyschool-56835.firebasestorage.app',
    measurementId: 'G-98HG8J1JQB',
  );
}
